version: '3'
services:
     mongo-container:
         image: mongo
         ports:
          - 27017:27017
         environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

     mongo-express-container:
          image: mongo-express
          ports:
           - 8081:8081
          environment:
           - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
           - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
           - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
           - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
           - ME_CONFIG_MONGODB_SERVER=mongo-container